In [33]:
import requests

In [ ]:
url = "http://data4library.kr/api/loanItemSrch?format=json&starDt=2021-04-01&endDt=2021-04-30&age=20&authKey=" # API 키 입력 필요

In [35]:
r = requests.get(url)

In [36]:
data = r.json()
print(data)

{'response': {'request': {'startDt': '2016-01-01', 'endDt': '2021-04-30', 'age': '20', 'pageNo': 1, 'pageSize': 200, 'format': 'json'}, 'resultNum': 200, 'numFound': 5000, 'docs': [{'doc': {'no': 1, 'ranking': '1', 'bookname': '나미야 잡화점의 기적 :히가시노 게이고 장편소설 ', 'authors': '지은이: 히가시노 게이고 ;옮긴이: 양윤옥', 'publisher': '현대문학', 'publication_year': '2012', 'isbn13': '9788972756194', 'addition_symbol': '03830', 'vol': '', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'http://image.aladin.co.kr/product/15848/6/cover/k622533431_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=1902173', 'loan_count': '38164'}}, {'doc': {'no': 2, 'ranking': '2', 'bookname': '채식주의자:한강 연작소설', 'authors': '한강', 'publisher': '창비', 'publication_year': '2007', 'isbn13': '9788936433598', 'addition_symbol': '03810', 'vol': '', 'class_no': '813.6', 'class_nm': '문학 > 한국문학 > 소설', 'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/033/094/03309417.jpg?type=m1&udate=20180609', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=2155671', 'loan_count': '25468'}}, {'doc': {'no': 3, 'ranking': '3', 'bookname': '미움받을 용기 :자유롭고 행복한 삶을 위한 아들러의 가르침 ', 'authors': '기시미 이치로,전경아 옮김', 'publisher': '인플루엔셜', 'publication_year': '2014', 'isbn13': '9788996991342', 'addition_symbol': '13180', 'vol': '', 'class_no': '189.2', 'class_nm': '철학 > 심리학 > 응용심리학 일반', 'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/083/399/08339910.jpg?type=m1&udate=20180616', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=2396926', 'loan_count': '23173'}}, {'doc': {'no': 4, 'ranking': '4', 'bookname': '7년의 밤 :정유정 장편소설 ', 'authors': '지은이: 정유정', 'publisher': '은행나무', 'publication_year': '2011', 'isbn13': '9788956604992', 'addition_symbol': '03810', 'vol': '', 'class_no': '813.7', 'class_nm': '문학 > 한국문학 > 소설', 'bookImageURL': 'http://image.aladin.co.kr/product/14712/55/cover/k202532053_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=1153285', 'loan_count': '22402'}}, {'doc': {'no': 5, 'ranking': '5', 'bookname': '스물아홉 생일, 1년 후 죽기로 결심했다 ', 'authors': '하야마 아마리 지음 ;장은주 옮김', 'publisher': '위즈덤하우스', 'publication_year': '2012', 'isbn13': '9788959136896', 'addition_symbol': '03830', 'vol': '', 'class_no': '838', 'class_nm': '문학 > 일본문학 > 르포르타주 및 기타', 'bookImageURL': 'http://image.aladin.co.kr/product/12354/77/cover/k612531359_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=1857068', 'loan_count': '22265'}}, {'doc': {'no': 6, 'ranking': '6', 'bookname': '소년이 온다 :한강 장편소설 ', 'authors': '지은이: 한강', 'publisher': '창비', 'publication_year': '2014', 'isbn13': '9788936434120', 'addition_symbol': '03810', 'vol': '', 'class_no': '813.62', 'class_nm': '문학 > 한국문학 > 소설', 'bookImageURL': 'http://image.aladin.co.kr/product/4086/97/cover/8936434128_2.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=2037399', 'loan_count': '21919'}}, {'doc': {'no': 7, 'ranking': '7', 'bookname': '82년생 김지영 :조남주 장편소설 ', 'authors': '지은이: 조남주', 'publisher': '민음사', 'publication_year': '2016', 'isbn13': '9788937473135', 'addition_symbol': '04810', 'vol': '', 'class_no': '813.7', 'class_nm': '문학 > 한국문학 > 소설', 'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/112/111/11211133.jpg?type=m1&udate=20180530', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3369923', 'loan_count': '21738'}}, {'doc': {'no': 8, 'ranking': '8', 'bookname': '종의 기원 =정유정 장편소설 /The origin of species ', 'authors': '지은이: 정유정', 'publisher': '은행나무', 'publication_year': '2016', 'isbn13': '9788956609959', 'addition_symbol': '03810', 'vol': '', 'class_no': '813.7', 'class_nm': '문학 > 한국문학 > 소설', 'bookImageURL': 'http://image.aladin.co.kr/product/7492/9/cover/8956609950_2.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3151708', 'loan_count': '19966'}}, {'doc': {'no': 9, 'ranking': '9', 'bookname': '언어의 온도 :말과 글에는 나름의 따뜻함과 차가움이 있다 ', 'authors': '지은이: 이기주', 'publisher': '말글터', 'publication_year': '2016', 'isbn13': '9791195522125', 'addition_symbol': '03810', 'vol': '', 'class_no': '818', 'class_nm': '문학 > 한국문학 > 르포르타주 및 기타', 'bookImageURL': 'http://image.aladin.co.kr/product/14842/6/cover/k742532452_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3278940', 'loan_count': '19681'}}, {'doc': {'no': 10, 'ranking': '10', 'bookname': '쇼코의 미소 :최은영 소설 ', 'authors': '지은이: 최은영', 'publisher': '문학동네', 'publication_year': '2016', 'isbn13': '9788954641630', 'addition_symbol': '03810', 'vol': '', 'class_no': '813.7', 'class_nm': '문학 > 한국문학 > 소설', 'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/107/859/10785953.jpg?type=m1&udate=20180717', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3190615', 'loan_count': '19312'}}, {'doc': {'no': 11, 'ranking': '11', 'bookname': '자존감 수업 :하루에 하나, 나를 사랑하게 되는 자존감 회복 훈련 ', 'authors': '윤홍균 지음', 'publisher': '심플라이프', 'publication_year': '2016', 'isbn13': '9791186757093', 'addition_symbol': '03190', 'vol': '', 'class_no': '182.1', 'class_nm': '철학 > 심리학 > 차이심리학', 'bookImageURL': 'http://image.aladin.co.kr/product/8679/31/cover/k372535696_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3320490', 'loan_count': '18867'}}, {'doc': {'no': 12, 'ranking': '12', 'bookname': '가면산장 살인사건 ', 'authors': '지은이: 히가시노 게이고 ;옮긴이: 김난주', 'publisher': '재인', 'publication_year': '2014', 'isbn13': '9788990982575', 'addition_symbol': '03830', 'vol': '', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'http://image.aladin.co.kr/product/4745/51/cover/899098257x_2.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=2427470', 'loan_count': '18856'}}, {'doc': {'no': 13, 'ranking': '13', 'bookname': '라플라스의 마녀 :히가시노 게이고 장편소설 ', 'authors': '지은이: 히가시노 게이고 ;옮긴이: 양윤옥', 'publisher': '현대문학', 'publication_year': '2016', 'isbn13': '9788972757573', 'addition_symbol': '03830', 'vol': '', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'http://image.aladin.co.kr/product/7288/55/cover/8972757578_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3107992', 'loan_count': '18113'}}, {'doc': {'no': 14, 'ranking': '14', 'bookname': '오베라는 남자 :프레드릭 배크만 장편소설 ', 'authors': '지은이: 프레드릭 배크만 ;옮긴이: 최민우', 'publisher': '다산북스', 'publication_year': '2015', 'isbn13': '9791130605210', 'addition_symbol': '03850', 'vol': '', 'class_no': '859.7', 'class_nm': '문학 > 독일문학 > 기타 게르만 문학', 'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/090/537/09053751.jpg?type=m1&udate=20180717', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=2396935', 'loan_count': '17873'}}, {'doc': {'no': 15, 'ranking': '15', 'bookname': '살인자의 기억법 :김영하 장편소설 ', 'authors': '지은이: 김영하', 'publisher': '문학동네', 'publication_year': '2013', 'isbn13': '9788954622035', 'addition_symbol': '03810', 'vol': '', 'class_no': '813.62', 'class_nm': '문학 > 한국문학 > 소설', 'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/072/622/07262295.jpg?type=m1&udate=20180314', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=1962014', 'loan_count': '17712'}}, {'doc': {'no': 16, 'ranking': '16', 'bookname': '아몬드 :손원평 장편소설 ', 'authors': '지은이: 손원평', 'publisher': '창비', 'publication_year': '2017', 'isbn13': '9788936434267', 'addition_symbol': '03810', 'vol': '', 'class_no': '813.7', 'class_nm': '문학 > 한국문학 > 소설', 'bookImageURL': 'http://image.aladin.co.kr/product/16839/4/cover/k492534773_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3423096', 'loan_count': '16650'}}, {'doc': {'no': 17, 'ranking': '17', 'bookname': '바깥은 여름 :김애란 소설 ', 'authors': '지은이: 김애란', 'publisher': '문학동네', 'publication_year': '2017', 'isbn13': '9788954646079', 'addition_symbol': '03810', 'vol': '', 'class_no': '813.7', 'class_nm': '문학 > 한국문학 > 소설', 'bookImageURL': 'http://image.aladin.co.kr/product/15533/81/cover/k852533629_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3451595', 'loan_count': '15769'}}, {'doc': {'no': 18, 'ranking': '18', 'bookname': '사피엔스 :유인원에서 사이보그까지, 인간 역사의 대담하고 위대한 질문 ', 'authors': '지은이: 유발 하라리 ;옮긴이: 조현욱', 'publisher': '김영사', 'publication_year': '2015', 'isbn13': '9788934972464', 'addition_symbol': '03900', 'vol': '', 'class_no': '909', 'class_nm': '역사 > 역사 > 세계사, 세계문화사', 'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/097/807/09780781.jpg?type=m1&udate=20180721', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3027835', 'loan_count': '15485'}}, {'doc': {'no': 19, 'ranking': '19', 'bookname': '나는 나로 살기로 했다 :냉담한 현실에서 어른살이를 위한 to do list ', 'authors': '글·그림: 김수현', 'publisher': '마음의숲', 'publication_year': '2016', 'isbn13': '9791187119845', 'addition_symbol': '03810', 'vol': '', 'class_no': '818', 'class_nm': '문학 > 한국문학 > 르포르타주 및 기타', 'bookImageURL': 'http://image.aladin.co.kr/product/16751/86/cover/k642534567_2.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3395679', 'loan_count': '15301'}}, {'doc': {'no': 20, 'ranking': '20', 'bookname': '왜 나는 너를 사랑하는가', 'authors': '알랭 드 보통 [지음];정영목 옮김', 'publisher': '청미래', 'publication_year': '2007', 'isbn13': '9788986836240', 'addition_symbol': '03840', 'vol': '', 'class_no': '843', 'class_nm': '문학 > 영미문학 > 소설', 'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/030/257/03025716.jpg?type=m1&udate=20180227', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=2130072', 'loan_count': '14795'}}, {'doc': {'no': 21, 'ranking': '21', 'bookname': '개인주의자 선언 :판사 문유석의 일상유감 ', 'authors': '지은이: 문유석', 'publisher': '문학동네', 'publication_year': '2015', 'isbn13': '9788954637756', 'addition_symbol': '03300', 'vol': '', 'class_no': '304', 'class_nm': '사회과학 > 사회과학 > 강연집, 수필집, 연설문집', 'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/095/957/09595780.jpg?type=m1&udate=20180717', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=2869604', 'loan_count': '13821'}}, {'doc': {'no': 22, 'ranking': '22', 'bookname': '창문 넘어 도망친 100세 노인 :요나스 요나손 장편소설 ', 'authors': '지은이: 요나스 요나손 ;옮긴이: 임호경', 'publisher': '열린책들', 'publication_year': '2013', 'isbn13': '9788932916194', 'addition_symbol': '03850', 'vol': '', 'class_no': '859.7', 'class_nm': '문학 > 독일문학 > 기타 게르만 문학', 'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/072/647/07264703.jpg?type=m1&udate=20180717', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=1959802', 'loan_count': '13773'}}, {'doc': {'no': 23, 'ranking': '23', 'bookname': '미 비포 유 ', 'authors': '조조 모예스 지음 ;김선형 옮김', 'publisher': '살림', 'publication_year': '2013', 'isbn13': '9788952227829', 'addition_symbol': '03840', 'vol': '', 'class_no': '843.6', 'class_nm': '문학 > 영미문학 > 소설', 'bookImageURL': 'http://image.aladin.co.kr/product/3502/92/cover/k852535760_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=2012732', 'loan_count': '13677'}}, {'doc': {'no': 24, 'ranking': '24', 'bookname': '어떻게 살 것인가 ', 'authors': '지은이: 유시민', 'publisher': '아름다운사람들', 'publication_year': '2013', 'isbn13': '9788965132288', 'addition_symbol': '03810', 'vol': '', 'class_no': '340.4', 'class_nm': '사회과학 > 정치학 > 정치학', 'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/071/503/07150363.jpg?type=m1&udate=20151014', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=1913291', 'loan_count': '13620'}}, {'doc': {'no': 25, 'ranking': '25', 'bookname': '설민석의 조선왕조실록 :대한민국이 선택한 역사 이야기 ', 'authors': '지은이: 설민석', 'publisher': '세계사', 'publication_year': '2016', 'isbn13': '9788933870693', 'addition_symbol': '03910', 'vol': '', 'class_no': '911.052', 'class_nm': '역사 > 아시아(아세아) > 한국', 'bookImageURL': 'http://image.aladin.co.kr/product/8749/45/cover/8933870695_3.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3238806', 'loan_count': '13375'}}, {'doc': {'no': 26, 'ranking': '26', 'bookname': '지적 대화를 위한 넓고 얕은 지식', 'authors': '채사장 지음', 'publisher': '한빛비즈', 'publication_year': '2014', 'isbn13': '9788994120966', 'addition_symbol': '13100', 'vol': '', 'class_no': '001.3', 'class_nm': '총류 > 총류 > 지식, 학문 일반', 'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/084/030/08403038.jpg?type=m1&udate=20171223', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=2396928', 'loan_count': '13142'}}, {'doc': {'no': 27, 'ranking': '27', 'bookname': '1Q84 :무라카미 하루키 장편소설', 'authors': '지은이: 무라카미 하루키 ;옮긴이: 양윤옥', 'publisher': '문학동네', 'publication_year': '2009', 'isbn13': '9788954608640', 'addition_symbol': '04830', 'vol': '1', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/060/537/06053729.jpg?type=m1&udate=20130406', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=2370295', 'loan_count': '12964'}}, {'doc': {'no': 28, 'ranking': '28', 'bookname': '비행운 :김애란 소설집 ', 'authors': '지은이: 김애란', 'publisher': '문학과지성사', 'publication_year': '2012', 'isbn13': '9788932023151', 'addition_symbol': '03810', 'vol': '', 'class_no': '813.7', 'class_nm': '문학 > 한국문학 > 소설', 'bookImageURL': 'http://image.aladin.co.kr/product/1801/21/cover/8932023158_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=1855307', 'loan_count': '12887'}}, {'doc': {'no': 29, 'ranking': '29', 'bookname': '상실의 시대 :무라카미 하루키 장편소설 ', 'authors': '지은이: 무라카미 하루키 ;옮긴이: 유유정', 'publisher': '문학사상', 'publication_year': '2011', 'isbn13': '9788970123691', 'addition_symbol': '03830', 'vol': '', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/000/203/00020349.jpg?type=m1&udate=20120904', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=863463', 'loan_count': '12526'}}, {'doc': {'no': 30, 'ranking': '30', 'bookname': '당신, 거기 있어 줄래요? :기욤 뮈소 장편소설 ', 'authors': '지은이: 기욤 뮈소 ;옮긴이: 전미연', 'publisher': '밝은세상', 'publication_year': '2007', 'isbn13': '9788984370791', 'addition_symbol': '03860', 'vol': '', 'class_no': '863', 'class_nm': '문학 > 프랑스문학 > 소설', 'bookImageURL': 'http://image.aladin.co.kr/product/90/59/cover/8984370797_2.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=2103010', 'loan_count': '12394'}}, {'doc': {'no': 31, 'ranking': '31', 'bookname': '지적 대화를 위한 넓고 얕은 지식', 'authors': '채사장 지음', 'publisher': '한빛비즈', 'publication_year': '2015', 'isbn13': '9788994120997', 'addition_symbol': '13100', 'vol': '2', 'class_no': '001.3', 'class_nm': '총류 > 총류 > 지식, 학문 일반', 'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/086/571/08657103.jpg?type=m1&udate=20171111', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=2396939', 'loan_count': '12135'}}, {'doc': {'no': 32, 'ranking': '32', 'bookname': '죽여 마땅한 사람들 ', 'authors': '피터 스완슨 지음 ;노진선 옮김', 'publisher': '푸른숲', 'publication_year': '2016', 'isbn13': '9791156756552', 'addition_symbol': '03840', 'vol': '', 'class_no': '843.6', 'class_nm': '문학 > 영미문학 > 소설', 'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/107/698/10769874.jpg?type=m1&udate=20171128', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3202062', 'loan_count': '12059'}}, {'doc': {'no': 33, 'ranking': '33', 'bookname': '빅 픽처 :더글라스 케네디 장편소설 ', 'authors': '지은이: 더글라스 케네디 ;옮긴이: 조동섭', 'publisher': '밝은 세상', 'publication_year': '2010', 'isbn13': '9788984371026', 'addition_symbol': '03840', 'vol': '', 'class_no': '843.5', 'class_nm': '문학 > 영미문학 > 소설', 'bookImageURL': 'http://image.aladin.co.kr/product/714/36/cover/8984371025_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=1072294', 'loan_count': '12055'}}, {'doc': {'no': 34, 'ranking': '34', 'bookname': '28 :정유정 장편소설 ', 'authors': '지은이: 정유정', 'publisher': '은행나무', 'publication_year': '2013', 'isbn13': '9788956607030', 'addition_symbol': '03810', 'vol': '', 'class_no': '813.7', 'class_nm': '문학 > 한국문학 > 소설', 'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/072/241/07224178.jpg?type=m1&udate=20141022', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=1945948', 'loan_count': '12032'}}, {'doc': {'no': 35, 'ranking': '35', 'bookname': '돌이킬 수 없는 약속 :야쿠마루 가쿠 장편소설 ', 'authors': '저자: 야쿠마루 가쿠 ;옮긴이: 김성미', 'publisher': 'Book plaza(북플라자)', 'publication_year': '2017', 'isbn13': '9788998274795', 'addition_symbol': '03830', 'vol': '', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'http://image.aladin.co.kr/product/10174/56/cover/s572533950_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3411733', 'loan_count': '11588'}}, {'doc': {'no': 36, 'ranking': '36', 'bookname': '용의자 X의 헌신', 'authors': '히가시노 게이고 지음;양억관 옮김', 'publisher': '현대문학', 'publication_year': '2006', 'isbn13': '9788972753698', 'addition_symbol': '03830', 'vol': '', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'http://image.aladin.co.kr/product/67/47/cover/8972753696_3.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=2080012', 'loan_count': '11460'}}, {'doc': {'no': 37, 'ranking': '37', 'bookname': '구해줘:기욤 뮈소 장편소설', 'authors': '기욤 뮈소 지음;윤미연 옮김', 'publisher': '밝은세상', 'publication_year': '2006', 'isbn13': '9788984370753', 'addition_symbol': '03860', 'vol': '', 'class_no': '863', 'class_nm': '문학 > 프랑스문학 > 소설', 'bookImageURL': 'http://image.aladin.co.kr/product/10392/11/cover/k552536996_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=964470', 'loan_count': '11365'}}, {'doc': {'no': 38, 'ranking': '38', 'bookname': '여덟 단어 :인생을 대하는 우리의 자세 ', 'authors': '박웅현 지음', 'publisher': '북하우스 퍼블리셔스', 'publication_year': '2013', 'isbn13': '9788956056531', 'addition_symbol': '03810', 'vol': '', 'class_no': '818', 'class_nm': '문학 > 한국문학 > 르포르타주 및 기타', 'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/072/024/07202413.jpg?type=m1&udate=20140911', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=1940355', 'loan_count': '11352'}}, {'doc': {'no': 39, 'ranking': '39', 'bookname': '악의 :히가시노 게이고 장편소설 ', 'authors': '히가시노 게이고 [지음] ;양윤옥 옮김', 'publisher': '현대문학', 'publication_year': '2008', 'isbn13': '9788972754190', 'addition_symbol': '03830', 'vol': '', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'http://image.aladin.co.kr/product/236/71/cover/8972754196_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=2220808', 'loan_count': '11309'}}, {'doc': {'no': 40, 'ranking': '40', 'bookname': '오직 두 사람 :김영하 소설 ', 'authors': '지은이: 김영하', 'publisher': '문학동네', 'publication_year': '2017', 'isbn13': '9788954645614', 'addition_symbol': '03810', 'vol': '', 'class_no': '813.62', 'class_nm': '문학 > 한국문학 > 소설', 'bookImageURL': 'http://image.aladin.co.kr/product/10949/50/cover/8954645615_2.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3440172', 'loan_count': '11151'}}, {'doc': {'no': 41, 'ranking': '41', 'bookname': '미움받을 용기 :사랑과 진정한 자립에 대한 아들러의 가르침', 'authors': '기시미 이치로,전경아 옮김', 'publisher': '인플루엔셜', 'publication_year': '2016', 'isbn13': '9791186560129', 'addition_symbol': '03180', 'vol': '2', 'class_no': '189.2', 'class_nm': '철학 > 심리학 > 응용심리학 일반', 'bookImageURL': 'http://image.aladin.co.kr/product/8123/68/cover/k782434140_2.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3139929', 'loan_count': '10984'}}, {'doc': {'no': 42, 'ranking': '42', 'bookname': '보노보노처럼 살다니 다행이야 ', 'authors': '김신회 지음', 'publisher': '다산북스', 'publication_year': '2017', 'isbn13': '9791130611853', 'addition_symbol': '03810', 'vol': '', 'class_no': '818', 'class_nm': '문학 > 한국문학 > 르포르타주 및 기타', 'bookImageURL': 'http://image.aladin.co.kr/product/12565/86/cover/k132532669_2.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3426376', 'loan_count': '10890'}}, {'doc': {'no': 43, 'ranking': '43', 'bookname': '내게 무해한 사람 :최은영 소설 ', 'authors': '지은이: 최은영', 'publisher': '문학동네', 'publication_year': '2018', 'isbn13': '9788954651820', 'addition_symbol': '03810', 'vol': '', 'class_no': '813.7', 'class_nm': '문학 > 한국문학 > 소설', 'bookImageURL': 'https://image.aladin.co.kr/product/15133/51/cover/8954651828_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3774162', 'loan_count': '10822'}}, {'doc': {'no': 44, 'ranking': '44', 'bookname': '피프티 피플 :정세랑 장편소설 ', 'authors': '지은이: 정세랑', 'publisher': '창비', 'publication_year': '2016', 'isbn13': '9788936434243', 'addition_symbol': '03810', 'vol': '', 'class_no': '813.7', 'class_nm': '문학 > 한국문학 > 소설', 'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/113/062/11306271.jpg?type=m1&udate=20180117', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3391014', 'loan_count': '10674'}}, {'doc': {'no': 45, 'ranking': '45', 'bookname': '말의 품격 :말과 사람과 품격에 대한 생각들 ', 'authors': '이기주 지음', 'publisher': '황소북스', 'publication_year': '2017', 'isbn13': '9788997092772', 'addition_symbol': '0

In [37]:
books = []
for d in data['response']['docs']:
    books.append(d['doc'])

In [38]:
import pandas as pd
books_df = pd.DataFrame(books)
books_df

,no,ranking,bookname,authors,publisher,publication_year,isbn13,addition_symbol,vol,class_no,class_nm,bookImageURL,bookDtlUrl,loan_count
0,1,1,나미야 잡화점의 기적 :히가시노 게이고 장편소설,지은이: 히가시노 게이고 ;옮긴이: 양윤옥,현대문학,2012,9788972756194,03830,,833.6,문학 > 일본문학 > 소설,http://image.aladin.co.kr/product/15848/6/cove...,https://data4library.kr/bookV?seq=1902173,38164
1,2,2,채식주의자:한강 연작소설,한강,창비,2007,9788936433598,03810,,813.6,문학 > 한국문학 > 소설,https://bookthumb-phinf.pstatic.net/cover/033/...,https://data4library.kr/bookV?seq=2155671,25468
2,3,3,미움받을 용기 :자유롭고 행복한 삶을 위한 아들러의 가르침,"기시미 이치로,전경아 옮김",인플루엔셜,2014,9788996991342,13180,,189.2,철학 > 심리학 > 응용심리학 일반,https://bookthumb-phinf.pstatic.net/cover/083/...,https://data4library.kr/bookV?seq=2396926,23173
3,4,4,7년의 밤 :정유정 장편소설,지은이: 정유정,은행나무,2011,9788956604992,03810,,813.7,문학 > 한국문학 > 소설,http://image.aladin.co.kr/product/14712/55/cov...,https://data4library.kr/bookV?seq=1153285,22402
4,5,5,"스물아홉 생일, 1년 후 죽기로 결심했다",하야마 아마리 지음 ;장은주 옮김,위즈덤하우스,2012,9788959136896,03830,,838,문학 > 일본문학 > 르포르타주 및 기타,http://image.aladin.co.kr/product/12354/77/cov...,https://data4library.kr/bookV?seq=1857068,22265
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,196,공중그네:오쿠다 히데오 장편소설,오쿠다 히데오 지음;이영미 옮김,은행나무,2005,9788956601021,03830,,833.6,문학 > 일본문학 > 소설,https://bookthumb-phinf.pstatic.net/cover/014/...,https://data4library.kr/bookV?seq=833020,5301
196,197,197,내 심장을 쏴라 :정유정 장편소설,지은이: 정유정,은행나무,2009,9788956602998,03810,,813.6,문학 > 한국문학 > 소설,http://image.aladin.co.kr/product/364/94/cover...,https://data4library.kr/bookV?seq=2298480,5298
197,198,198,우울할 땐 뇌과학,앨릭스 코브 지음 ;정지인 옮김,푸른숲,2018,9791156757344,03180,,513.8525,기술과학 > 의학 > 내과학,http://image.aladin.co.kr/product/13494/71/cov...,https://data4library.kr/bookV?seq=3701387,5286
198,199,199,피로사회,지은이: 한병철 ;옮긴이: 김태환,문학과지성사,2012,9788932022888,03100,,104,"철학 > 철학 > 강연집, 수필집",https://bookthumb-phinf.pstatic.net/cover/068/...,https://data4library.kr/bookV?seq=1241509,5275
199,200,200,경애의 마음 :김금희 장편소설,지은이: 김금희,창비,2018,9788936434311,03810,,813.7,문학 > 한국문학 > 소설,http://image.aladin.co.kr/product/14658/79/cov...,https://data4library.kr/bookV?seq=3754576,5263

In [39]:
books_df.to_json('20s_best_book.json')

In [40]:
import gdown
gdown.download('https://bit.ly/3q9SZix', '20s_best_book.json', quiet=False)

Downloading...
From: https://bit.ly/3q9SZix
To: /Users/ryu/Coding/Python/3-Idiots/1st Homework - Web Scraping/20s_best_book.json
100%|██████████| 92.9k/92.9k [00:00<00:00, 1.03MB/s]

'20s_best_book.json'

In [41]:
import pandas as pd
books_df = pd.read_json('20s_best_book.json')
books_df.head()

,no,ranking,bookname,authors,publisher,publication_year,isbn13,addition_symbol,vol,class_no,class_nm,loan_count,bookImageURL
0,1,1,우리가 빛의 속도로 갈 수 없다면 :김초엽 소설,지은이: 김초엽,허블,2019,9791190090018,03810,,813.7,문학 > 한국문학 > 소설,461,https://image.aladin.co.kr/product/19359/16/co...
1,2,2,달러구트 꿈 백화점.이미예 장편소설,지은이: 이미예,팩토리나인,2020,9791165341909,03810,,813.7,문학 > 한국문학 > 소설,387,https://image.aladin.co.kr/product/24512/70/co...
2,3,3,지구에서 한아뿐 :정세랑 장편소설,지은이: 정세랑,난다,2019,9791188862290,03810,,813.7,문학 > 한국문학 > 소설,383,https://image.aladin.co.kr/product/19804/82/co...
3,4,4,"시선으로부터, :정세랑 장편소설",지은이: 정세랑,문학동네,2020,9788954672214,03810,,813.7,문학 > 한국문학 > 소설,370,https://image.aladin.co.kr/product/24131/37/co...
4,5,5,아몬드 :손원평 장편소설,지은이: 손원평,창비,2017,9788936434267,03810,,813.7,문학 > 한국문학 > 소설,365,http://image.aladin.co.kr/product/16839/4/cove...

In [42]:
books = books_df[['no', 'ranking', 'bookname', 'authors', 'publisher', 'publication_year', 'isbn13']]
books.head()

,no,ranking,bookname,authors,publisher,publication_year,isbn13
0,1,1,우리가 빛의 속도로 갈 수 없다면 :김초엽 소설,지은이: 김초엽,허블,2019,9791190090018
1,2,2,달러구트 꿈 백화점.이미예 장편소설,지은이: 이미예,팩토리나인,2020,9791165341909
2,3,3,지구에서 한아뿐 :정세랑 장편소설,지은이: 정세랑,난다,2019,9791188862290
3,4,4,"시선으로부터, :정세랑 장편소설",지은이: 정세랑,문학동네,2020,9788954672214
4,5,5,아몬드 :손원평 장편소설,지은이: 손원평,창비,2017,9788936434267

In [43]:
books_df.loc[[0, 1], ['bookname', 'authors']]

                      bookname   authors
0  우리가 빛의 속도로 갈 수 없다면 :김초엽 소설   지은이: 김초엽
1         달러구트 꿈 백화점.이미예 장편소설   지은이: 이미예

In [44]:
books_df.loc[0:1, ['bookname', 'authors']]

                      bookname   authors
0  우리가 빛의 속도로 갈 수 없다면 :김초엽 소설   지은이: 김초엽
1         달러구트 꿈 백화점.이미예 장편소설   지은이: 이미예

In [45]:
books = books_df.loc[:, 'no':'isbn13']
books.head()

,no,ranking,bookname,authors,publisher,publication_year,isbn13
0,1,1,우리가 빛의 속도로 갈 수 없다면 :김초엽 소설,지은이: 김초엽,허블,2019,9791190090018
1,2,2,달러구트 꿈 백화점.이미예 장편소설,지은이: 이미예,팩토리나인,2020,9791165341909
2,3,3,지구에서 한아뿐 :정세랑 장편소설,지은이: 정세랑,난다,2019,9791188862290
3,4,4,"시선으로부터, :정세랑 장편소설",지은이: 정세랑,문학동네,2020,9788954672214
4,5,5,아몬드 :손원평 장편소설,지은이: 손원평,창비,2017,9788936434267

In [46]:
books_df.loc[::2, 'no':'isbn13'].head()

,no,ranking,bookname,authors,publisher,publication_year,isbn13
0,1,1,우리가 빛의 속도로 갈 수 없다면 :김초엽 소설,지은이: 김초엽,허블,2019,9791190090018
2,3,3,지구에서 한아뿐 :정세랑 장편소설,지은이: 정세랑,난다,2019,9791188862290
4,5,5,아몬드 :손원평 장편소설,지은이: 손원평,창비,2017,9788936434267
6,7,7,목소리를 드릴게요 :정세랑 소설집,지은이: 정세랑,아작,2020,9791165300005
8,9,9,선량한 차별주의자,김지혜 지음,창비,2019,9788936477196

In [47]:
import requests
isbn = 9791190090018
url = 'http://www.yes24.com/Product/Search?domain=BOOK&query={}'
r = requests.get(url.format(isbn))
print(r.text)

	<!DOCTYPE html >
	<html lang="ko">

<head>
	<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<meta http-equiv="Accept-CH" content="dpr, width, viewport-width, rtt, downlink, ect, UA, UA-Platform, UA-Arch, UA-Model, UA-Mobile, UA-Full-Version" />
	<meta http-equiv="Accept-CH-Lifetime" content="86400" />
	<meta name="referrer" content="unsafe-url" />
    <meta name="viewport" content="width=1170" />

    <title> 9791190090018 - 예스24</title>

	<meta name="title" content="예스24" />
	<meta name="description" content="도서, 티켓, 음반, 굿즈, 커뮤니티까지 문화 전반을 아우르는 국내 대표 문화콘텐츠 플랫폼, 아낌없는 혜택과 총알배송을 경험해보세요." />
	<meta name="keywords" content="인터넷 서점, 온라인 쇼핑, 상품 추천, 쇼핑몰, 상품 검색, 도서 정보, 국내도서, 외국도서, 전자책, eBook, 이북, 크레마, 공연, 콘서트, 뮤지컬, 음반, 예매, DVD, 블루레이, 예스24, YES24, 교보문고, 알라딘, 리센스, 예스24 도서용품, 친환경 PB 브랜드, 사은품, 굿즈" />


	<link title="YES24" rel="search" type="application/opensearchdescription+xml" href="//www.yes24.com/OpensearchDescription.xml">

	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/m/common/xds.min.js?v=20210909"></script>
	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery-1.12.4.min.js"></script>

	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.menu-aim.js?v=20250613"></script>
	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.easing.1.3.min.js?v=20250613"></script>
	<script type="text/javascript" src="https://www.yes24.com/JavaScript/util.js?v=20251114_a"></script>
	<script type="text/javascript" charset="euc-kr" src="https://www.yes24.com/JavaScript/Yes_header.js?v=20250613"></script>
	<script type="text/javascript" src="https://www.yes24.com/JavaScript/hiveSlide.js?v=20250618"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/common/jqueryExtendsPC.min.js?v=20250618"></script>
	<script type="text/javascript" src="https://www.yes24.com/JavaScript/recentviewgoods.js?v=20250613"></script>
    <script type="text/javascript" src="https://www.yes24.com/Javascript/Search/bulletSearch.js?v=20260107"></script>
	<script type="text/javascript" src="https://www.yes24.com/24/Scripts/YES24.Common-1.6.js?v=20251201"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/common/RedirectWebSiteList.min.js?v=20251111_1"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/common/RedirectWebSite.min.js?v=20251111_1"></script>
	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/d/scl/simplebar.js?v=20250613"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/common/frontCommon.js?v=20260205_b"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/common/addon.js?v=20260204" charset="UTF-8"></script>

	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.lazyload.min.1.9.7.js?v=20250613"></script>

	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/p/ui/openinside.pack.js?v=20251111_1"></script>
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/Newstyle.css?v=20250818" charset="euc-kr"/>
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/renewHack.css?v=20250818" />

	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/yesCom.css?v=20260113" />
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/yesHeaderN4.css?v=20251208" />
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/yesFooterN4.css?v=20260205" />
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/wideLayout.css?v=20250818" />
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/simplebar.css?v=20250818" />

	<!--[if IE]>
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/renewHack_ie.css?v=20250818" />
	<![endif]-->

	<link href="https://image.yes24.com/sysimage/renew/gnb/favicon_n.ico" type="image/x-icon" rel="shortcut icon" />

	<script type="text/javascript">
		var YesData = new function() {
			var _HTTP_URL = "https://www.yes24.com";
			var _BLOG_URL = "https://blog.yes24.com/";
			var _IMG_HOST_IMG = "https://image.yes24.com";
			var _IsWelcomePage = "False";
			var _MEM_AGE = 0;
			var _PID = "";
			var _ParenerInfomagion ={};
			var _NOW_HTTP_URL = "https://www.yes24.com";
			var _IsdevServer = "False";
			var _IsHttps = "True";

			this.HTTP_URL = function(){return _HTTP_URL;}
			this.NOW_HTTP_URL = function(){return _NOW_HTTP_URL;}
			this.BLOG_URL = function(){return _BLOG_URL;}
			this.IMG_HOST_IMG = function(){return _IMG_HOST_IMG;}
			this.IsHttps = function(){return _IsHttps;}
			this.IsWelcomePage = function(){return _IsWelcomePage;}
			this.MEM_AGE = function(){return _MEM_AGE;}
			this.PID = function(){return _PID;}
			this.ParenerInfomagion = function(){return _ParenerInfomagion;}
			this.IsdevServer = function(){return _IsdevServer;}
		}

		$(document).ready(function () {

		});//ready

		// 최근본 상품
		var recentViewGoods = new RecentViewGoods();

		// 광고창을 계속 불러올지 여부
		var SearchBarRenderingEnable = true;

		var USERNO = '';
		var IS_NATIVE_APPS = false;
		var is_debug = Boolean(1);
		// 브레이즈 위한 설정 값
		var TUSERNO = '';
		var isUnder14 = 'False';

	    // 스크립트 참조 여부 설정 값
	    var scToday = new Date().getFullYear() + "-" + ('0' + (new Date().getMonth() + 1)).slice(-2) + "-" + ('0' + (new Date().getDate())).slice(-2);
	    var scExpDate = "2023-07-06";   // 스크립트 참조 만료일 지정
	    var IsScExpDate = scToday > scExpDate ? false : true;
    </script>
	<script type="text/javascript" src="https://www.yes24.com/javascript/common.js?v=20260205_b"></script>
	<script type="text/javascript" src="https://www.yes24.com/JavaScript/headerSetting.js?v=20250916"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/logging/clickstream.min.js?v=20260326"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/logging/brazeSDK.js?v=20260210"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/logging/brazeHelper.js?v=20260210" defer></script>
	<script src="https://image.yes24.com/static/logging/airbridgeSDK.js?v=20260210"></script>
	<script src="https://image.yes24.com/static/logging/airbridgeHelper.js?v=20260210"></script>


	<!-- 광고 스크립트 - 공통 -->
        <!-- Google Tag Manager -->
    <script>
        (function (w, d, s, l, i) {
            w[l] = w[l] || []; w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            }); var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
                    'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-WM4K93V');
    </script>
    <!-- End Google Tag Manager -->
	<script async src="https://cdn.onetag.co.kr/0/tcs.js?eid=skxx6fnq6ueeskxx6fnq6u"></script>

<link rel='stylesheet' href='https://image.yes24.com/sysimage/yesUI/yesUI.css?v=20260224' type='text/css' media='all'><link rel='stylesheet' href='https://image.yes24.com/sysimage/yesUI/layout/pcBase.css?v=20260323' type='text/css' media='all'><link rel='stylesheet' href='https://image.yes24.com/sysimage/yesUI/search/search.css?v=220250818' type='text/css' media='all'></head>
<body>

	<!-- 광고 스크립트 - 공통 -->
     <!-- Google Tag Manager (noscript) -->
<noscript>
    <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WM4K93V" height="0" width="0" style="display:none;visibility:hidden"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<dl id="yesSkip">
	<dt>콘텐츠 바로가기</dt>
	<dd><a href="#wrapperContent">본문 바로가기</a></dd>
</dl>

<hr/>
<!-- !!!!!!!!!!########## 전체 페이지 영역 시작 ##########!!!!!!!!!! -->
<div id="yesWrap" class="">
	<div id="yesHeaderArea" style="">
	<!-- ########## TOPBANNER 영역 시작 ########## -->
	<section>
		<div id="upperBnWrap" style="display:none;">
			<div id="upperBnRoll">
				<div class="upperBnSet" style="display:none;">
	<div class="upperBnArea">
		<div class="upperBnSetLft" style="background-color:#f5f5ce"><a href="https://event.yes24.com/onlyApp" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0311_topbn_480x50_L_01.png" width="480" height="50" alt="도서앱"></a></div>
		<div class="upperBnSetRgt" style="background-color:#f7cce3"><a href="https://event.yes24.com/present?eventNo=267385" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0311_topbn_480x50_R_01.png" width="480" height="50" alt="폴더블독서등"></a></div>
	</div>
</div><div class="upperBnSet" style="display:none;">
	<div class="upperBnArea">
		<div class="upperBnSetLft" style="background-color:#c3e3f6"><a href="https://event.yes24.com/yesBenefit" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0311_topbn_480x50_L_02.png" width="480" height="50" alt="3월혜택"></a></div>
		<div class="upperBnSetRgt" style="background-color:#c6f1cc"><a href="https://event.yes24.com/present?eventNo=267385" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0311_topbn_480x50_R_02.png" width="480" height="50" alt="쿠션방석"></a></div>
	</div>
</div><div class="upperBnSet" style="display:none;">
	<div class="upperBnArea">
		<div class="upperBnSetLft" style="background-color:#fbf7df"><a href="https://event.yes24.com/detail?eventNo=267829" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0311_topbn_480x50_L_03.png" width="480" height="50" alt="젊은시인"></a></div>
		<div class="upperBnSetRgt" style="background-color:#f4d29d"><a href="https://event.yes24.com/present?eventNo=267385" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0311_topbn_480x50_R_03.png" width="480" height="50" alt="폴더블독서등"></a></div>
	</div>
</div>
			</div>
			<div class="upperClose"><a href="javascript:void(0);" onclick="hideUpperBn();"><em class="yBlind">TOP BANNER 닫기</em></a></div>
		</div>
	</section>
	<script type="text/javascript">
		function hideUpperBn() {
			setWcode('001_001');
			var todayDate = new Date();
			setCookie("UPPER_BN_SHOW", "OK", 1); // 오른쪽 숫자는 쿠키를 유지할 기간(day)을 설정합니다
			$("#upperBnWrap").css("display", "none");
		}

		if (getCookie("UPPER_BN_SHOW") == "") {
			$("#upperBnWrap").css("display","");
		}
		$('#upperBnRoll .upperBnSet').eq( Math.floor(Math.random()*$("#upperBnRoll .upperBnSet").length) ).show();

		//SSL 페이지에서 접근시 Top Banner 영역 제거
		if(location.href.indexOf("https://ssl.yes24.com/")> -1) {
			$("#upperBnWrap").remove();
		}
	</script>
	<!-- ########## TOPBANNER 영역 끝 ########## -->
	<!-- ########## HEADER 영역 시작 ########## -->
	<div id="yHeader">
		<h1><a class="logo" href="https://www.yes24.com/main/default.aspx" onClick="setWcode('001_004');"><svg role="img" aria-label="YES24" type="image/svg+xml"><image src="https://image.yes24.com/sysimage/renew/gnb/logoN4.png" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://image.yes24.com/sysimage/renew/gnb/logoN4.svg" width="200" height="103" alt="YES24"></image></svg></a></h1>
		<div id="yHeaderWrap">
			<!-- %%%%%%%%%% 해더 Top 영역 시작 %%%%%%%%%% -->
			<div class="yHeaderTop">
				<h2 class="yBlind">YES24 카테고리 리스트</h2>
					<ul class="cateLi" id="ulCategoryList"><li class="cate001"><a title="국내도서" href="https://www.yes24.com/Mall/Main/Book/001?CategoryNumber=001" onclick="setWcode('001_002_001')" ><em class="txt">국내도서</em></a></li><li class="cate002"><a title="외국도서" href="https://www.yes24.com/Mall/Main/Foreign/002?CategoryNumber=002"  onclick="setWcode('001_002_002')"  ><em class="txt">외국도서</em></a></li><li class="cate018"><a title="중고샵" href="https://www.yes24.com/Mall/Main/used/018?CategoryNumber=018" onclick="setWcode('001_002_011')" ><em class="txt">중고샵</em></a></li><li class="cate017"><a title="eBook" href="https://www.yes24.com/Mall/Main/eBook/017?CategoryNumber=017" onclick="setWcode('001_002_003')"  ><em class="txt">eBook</em></a></li><li class="cateCrC"><a title="크레마클럽" href="https://cremaclub.yes24.com/BookClub/Main" onclick="setWcode('001_002_016')"  ><em class="txt">크레마클럽</em></a></li><li class="cate003"><a title="CD/LP" href="https://www.yes24.com/Mall/Main/Music/003?CategoryNumber=003" onclick="setWcode('001_002_005')" ><em class="txt">CD/LP</em></a></li><li class="cate004"><a title="DVD/Blu-ray" href="https://www.yes24.com/Mall/Main/Dvd/004?CategoryNumber=004" onclick="setWcode('001_002_006')" ><em class="txt">DVD/BD</em></a></li><li class="cate006"><a title="GIFT" href="https://www.yes24.com/Mall/Main/Gift/006?CategoryNumber=006" onclick="setWcode('001_002_009')" ><em class="txt"><u>문구</u>/GIFT</em></a></li><li class="cateENT"><a title="티켓" href="http://ticket.yes24.com" onclick="setWcode('001_002_008')" target="_blank"  ><em class="txt">티켓</em><em class="ico_newW bgGNB">새창이동</em></a></li></ul>
				<h2 class="yBlind">YES24 유틸메뉴</h2>
				<ul class="utilLi">
					<li id="LoginText">
						<input type="hidden" id="hdfLoginYn" value="N" />

							<a href="https://www.yes24.com/Templates/FTLogin.aspx" onclick="setWcode('001_003_001')"><em class="txt">로그인</em></a>

					</li>

						<li><a href="https://www.yes24.com/Member/Join/Accept.aspx" onclick="setWcode('001_003_003')">회원가입</a></li>

					<li class="myPgGrp">
						<a href="javascript:void(0);" onclick="setWcode('001_003_013')"><em class="txt">마이페이지</em><em class="ico_arrD bgGNB">하위메뉴보기</em></a>
						<dl class="myPgDl">
							<dt><a href="https://www.yes24.com/Member/FTMypageMain.aspx" onclick="setWcode('001_003_013')"><em class="txt">마이페이지</em><em class="ico_arrU bgGNB">이동</em></a></dt>
							<dd>
								<ul>
									<li><a href="https://ssl.yes24.com/MyPageOrderList/MyPageOrderList" onclick="setWcode('001_003_004')">주문내역	 </a></li>
									<li><a href="https://www.yes24.com/Member/FTGoMyBlog.aspx?type=list" onclick="setWcode('001_003_005')" target="_blank">마이리스트   </a></li>
									<li><a href="https://www.yes24.com/Templates/FTMyAccount_1YESPoint.aspx" onclick="setWcode('001_003_006')">YES포인트    </a></li>
									<li><a href="https://www.yes24.com/Templates/FTMyAccount_1YESMoney.aspx" onclick="setWcode('001_003_007')">YES머니      </a></li>
									<li><a href="https://www.yes24.com/Templates/FTMyAccount_3GiftCard.aspx" onclick="setWcode('001_003_014')">YES상품권      </a></li>
									<li><a href="https://www.yes24.com/Templates/FTMyAccount_4Coupon.aspx" onclick="setWcode('001_003_008')">쿠폰         </a></li>
									<li><a href="https://www.yes24.com/Member/MyPage_reconfirmPW.aspx" onclick="setWcode('001_003_009')">회원정보     </a></li>
								</ul>
							</dd>
						</dl>
					</li>
					<li><a href="https://ssl.yes24.com/Cart/Cart" onclick="setWcode('001_003_010')" ><em class="txt">카트</em></a></li>
					<li><a href="https://ssl.yes24.com/MyPageOrderList/MyPageOrderList" onclick="setWcode('001_003_011')"><em class="txt">주문/배송</em></a></li>
					<li class="lastLi"><a href="https://www.yes24.com/Templates/FTCusMain.aspx?Wcode=001_003_012" onclick="setWcode('001_003_012')"><em class="txt">고객센터</em></a></li>
				</ul>
				<dl class="globalYesInfoDl">
					<dt><a href="javascript:void(0);" ><em class="txt">Global YES24</em><em class="ico_arr bgGNB">안내보기</em></a></dt>
					<dd>
						<div class="globalYesInfoContArea">
							<div class="globalYesInfoCont">
								<p class="yesInfo_tit">Global YES24는?</p>
								<p class="yesInfo_des">
									K-POP/K-Drama 관련상품(음반,도서,DVD)을<br/> 영문/중문 으로 이용하실 수 있습니다.
								</p>
								<div class="yesInfo_globalTxt">
									<p class="globalTxt_des">
										Korean wave shopping mall, sell the <br/>K-POP/K-Drama (CD,DVD,Blu-ray,Book)
										We aceept PayPal/UnionPay/Alipay<br/> and support English/Chinese Language service
									</p>
									<a href="https://global.yes24.com" target="_blank" onclick="setWcode('001_016_002')" class="btnC btn_blue"><span class="bWrap"><em class="txt">English</em></span></a>
									<p class="globalTxt_des">
									 作&#x4E3A;出&#x552E;正&#x89C4; K-POP/K-Drama 相&#x5173;(CD,&#x56FE;&#x4E66;,DVD) &#x97E9;流商品的&#x7F51;站, 支持 中文/英文 等海外&#x7ED3;&#x8D26;方式
									</p>
									<a href="https://cn.yes24.com" target="_blank" onclick="setWcode('001_016_003')" class="btnC btn_blue"><span class="bWrap"><em class="txt">中文</em></span></a>
                                    <p class="globalTxt_des">
									 Exclusive ticket sales for domestic and international pop artists
									</p>
									<a href="http://ticket.yes24.com/English?Gcode=009_205" target="_blank" onclick="setWcode('001_016_004')" class="btnC btn_blue"><span class="bWrap"><em class="txt">Global yesticket</em></span></a>
								</div>
							</div>
						</div>
					</dd>
				</dl>
			</div>
		   <!-- %%%%%%%%%% 해더 Top 영역 끝 %%%%%%%%%% -->
			<hr/>
			<!-- %%%%%%%%%% 해더 Mid 영역 시작 %%%%%%%%%% -->
			<div class="yHeaderMid">
				<div class="yesSearch">
					<form id="yesSForm" method="get" name="HeadForm" action="//www.yes24.com/product/search?" onsubmit="return check_search();" accept-charset="utf-8">
					<input type="hidden" id="keywordAd" name="keywordAd" value=""/>
					<input type="hidden" id="keyword" name="keyword" />
					<input type="hidden" id="domain" name="domain" value="ALL" />
					<input type="hidden" id="qdomain" name="qdomain" value="전체" />

					<fieldset>
					<legend>검색</legend>
					<span class="schIpt">
						<label><input type="text" title="YES24 검색어 입력" class="iptTxt" accesskey="s" id="query" name="query"
										maxlength="80" value="" style="ime-mode: active;" autocomplete="off"
										onfocus="showLatestSearchList();" onblur="blurSearchBar();"
										onkeydown="SearchBarRenderingEnableSet(false);init_searchbox();"
										onmousedown="SearchBarRenderingEnableSet(false);Common_init_searchbox();" /></label>
					</span>
					<div style="position:absolute;top:-1000em;left:0;width:1px;height:1px;overflow:hidden;">


						<script type="text/javascript" src="//adgirl.yes24.com/RealMedia/ads/adstream_mjx.ads/www.yes24.com/Header/SearchBar@x01" charset='euc-kr'></script>
						<script type="text/javascript">
							try {
								OAS_RICH("x01");
							} catch (e) { }
						</script>

					</div>
					<script type="text/javascript">
						var url = location.href;
						var reUrl = url.toLowerCase();

						$(document).ready(function () {
							//검색결과
						    if (reUrl.indexOf('/product/search') > -1 && reUrl.indexOf('/product/search/searchkeyword') <= 0) {
								SearchBarRenderingEnable = false;

								if (getParamValue("query") != undefined) {
									$("#query").val($("#hidSearchWord").val());
									fnGetValueDomain($("#hidSearchDomain").val());
									$("#domain").val($("#hidSearchDomain").val());
									$("#qdomain").val($("#hidSearchQdomain").val());
								}
							}
							if (SearchBarRenderingEnable == true) {
								fnSearchBarRendering();
							}
						});

						// 검색어 입력창에 포커스 시
						function SearchBarRenderingEnableSet(enable) {
							//광고 제거
							SearchBarRenderingEnable = enable;
							$("#ulSchScopeOpt").hide();
						}

						// 검색어 입력창 광고 노출
						function fnSearchBarRendering() {
							var seardtext = $('#hdSearchBarText').val();
							var bannerLink = $("#hdSearchBarLink").val();

							$('#query').val(seardtext);
							$('#query').addClass("iptTxt iptTxtAd");
							$('#keywordAd').val(bannerLink);
						}

						//검색창 선택 시
						function showLatestSearchList() {

In [48]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(r.text, 'html.parser')

In [49]:
prd_link = soup.find('a', attrs = {'class': 'gd_name'})
print(prd_link)

<a class="gd_name" href="/product/goods/74261416" onclick="wiseLogV2('S', '101_005_003_001', ''); setGoodsClickExtraCodeHub('032', '9791190090018', '74261416', '0',this);">우리가 빛의 속도로 갈 수 없다면</a>

In [50]:
print(prd_link['href'])

/product/goods/74261416

In [51]:
url = 'http://www.yes24.com'+ prd_link['href']
r = requests.get(url)
print(r.text)

	<!DOCTYPE html >
	<html lang="ko">

<head><link rel="canonical" href="https://www.yes24.com/product/goods/74261416"> <link rel="alternate" media="only screen and (max-width: 640px)"  href="https://m.yes24.com/goods/detail/74261416">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<meta http-equiv="Accept-CH" content="dpr, width, viewport-width, rtt, downlink, ect, UA, UA-Platform, UA-Arch, UA-Model, UA-Mobile, UA-Full-Version" />
	<meta http-equiv="Accept-CH-Lifetime" content="86400" />
	<meta name="referrer" content="unsafe-url" />
    <meta name="viewport" content="width=1170" />

    <title>우리가 빛의 속도로 갈 수 없다면 | 김초엽 | 허블 - 예스24 </title>


<meta name="title" content="우리가 빛의 속도로 갈 수 없다면"/>
<meta name="author" content="김초엽 저" />

<meta name="description" content="우리가 빛의 속도로 갈 수 없다면. “젊은 소설가의 첫 작품집이라고는 믿기지 않을 정도로 매끄럽게 이어지는 이야기 속에서 내가 생각하는 소설가의 눈과 입을 발견했다. 시선에서 질문까지, 모두 인상적이다.” -김연수(소설가)“마음을 다 맡기며 좋아할 수 있는 새..."/>

<meta name="keywords" content="한국문학의미래가될젊은작가,SF란시대의거울,해외문학상_우리작가,월간개발자_추천도서,YES24XEBS_대국민독서챌린지,크레마클럽에있어요,2020젊은작가TOP5,최신작알림신청인기작가,2021젊은작가TOP5,가을에어울리는책,내맘대로올해의책,2021한국문학의미래가될젊은작가,문학뉴스레터에소개된책,SF의우아한계보,KBS우리시대의소설,KBS2TV북유럽,표지예쁜책,MD의구매리스트,북클러버의선택,HERSTORY,책읽아웃,더울땐SF,소외된사람들을위하여,sf/미래물,김초엽 저, 허블, 광속불가,독서챌린지,오늘의작가상,우빛속,KBS북유럽,1190090015,9791190090018"/>

<!-- Facebook Interface -->
<meta property="og:title" content="우리가 빛의 속도로 갈 수 없다면 | 김초엽 | 허블 - 예스24" />
<meta property="og:type" content="book" />
<meta property="og:url" content="https://www.yes24.com/product/goods/74261416" />
<meta property="og:image" content="https://image.yes24.com/goods/74261416/xl" />
<meta property="og:site_name" content="예스24" />
<meta property="og:description" content="“젊은 소설가의 첫 작품집이라고는 믿기지 않을 정도로 매끄럽게 이어지는 이야기 속에서 내가 생각하는 소설가의 눈과 입을 발견했다. 시선에서 질문까지, 모두 인상적이다.” -김연수(소설가)“마음을 다 맡기며 좋아할 수 있는 새로운 작가를 만나서 벅차다.” -정세..." />
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="https://www.yes24.com/product/goods/74261416" />
<meta name="twitter:title" content="우리가 빛의 속도로 갈 수 없다면 | 김초엽 | 허블 - 예스24" />
<meta name="twitter:description" content="“젊은 소설가의 첫 작품집이라고는 믿기지 않을 정도로 매끄럽게 이어지는 이야기 속에서 내가 생각하는 소설가의 눈과 입을 발견했다. 시선에서 질문까지, 모두 인상적이다.” -김연수(소설가)“마음을 다 맡기며 좋아할 수 있는 새로운 작가를 만나서 벅차다.” -정세..." />
<meta name="twitter:image" content="https://image.yes24.com/goods/74261416/xl" />

<meta property="books:isbn" content="9791190090018"/>
<meta property="books:rating:value" content="9.4"/>
<meta property="books:rating:scale" content="10"/>
<meta property="books:rating:normalized_value" content="0"/>



	<link title="YES24" rel="search" type="application/opensearchdescription+xml" href="//www.yes24.com/OpensearchDescription.xml">

	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/m/common/xds.min.js?v=20210909"></script>
	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery-1.12.4.min.js"></script>

	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.menu-aim.js?v=20250613"></script>
	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.easing.1.3.min.js?v=20250613"></script>
	<script type="text/javascript" src="https://www.yes24.com/JavaScript/util.js?v=20251114_a"></script>
	<script type="text/javascript" charset="euc-kr" src="https://www.yes24.com/JavaScript/Yes_header.js?v=20250613"></script>
	<script type="text/javascript" src="https://www.yes24.com/JavaScript/hiveSlide.js?v=20250618"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/common/jqueryExtendsPC.min.js?v=20250618"></script>
	<script type="text/javascript" src="https://www.yes24.com/JavaScript/recentviewgoods.js?v=20250613"></script>
    <script type="text/javascript" src="https://www.yes24.com/Javascript/Search/bulletSearch.js?v=20260107"></script>
	<script type="text/javascript" src="https://www.yes24.com/24/Scripts/YES24.Common-1.6.js?v=20251201"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/common/RedirectWebSiteList.min.js?v=20251111_1"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/common/RedirectWebSite.min.js?v=20251111_1"></script>
	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/d/scl/simplebar.js?v=20250613"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/common/frontCommon.js?v=20260205_b"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/common/addon.js?v=20260204" charset="UTF-8"></script>

	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.lazyload.min.1.9.7.js?v=20250613"></script>

	<script type="text/javascript" src="https://image.yes24.com/sysimage/Contents/Scripts/p/ui/openinside.pack.js?v=20251111_1"></script>
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/Newstyle.css?v=20250818" charset="euc-kr"/>
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/renewHack.css?v=20250818" />

	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/yesCom.css?v=20260113" />
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/yesHeaderN4.css?v=20251208" />
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/yesFooterN4.css?v=20260205" />
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/wideLayout.css?v=20250818" />
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/simplebar.css?v=20250818" />

	<!--[if IE]>
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/renewHack_ie.css?v=20250818" />
	<![endif]-->

	<link href="https://image.yes24.com/sysimage/renew/gnb/favicon_n.ico" type="image/x-icon" rel="shortcut icon" />

	<script type="text/javascript">
		var YesData = new function() {
			var _HTTP_URL = "https://www.yes24.com";
			var _BLOG_URL = "https://blog.yes24.com/";
			var _IMG_HOST_IMG = "https://image.yes24.com";
			var _IsWelcomePage = "False";
			var _MEM_AGE = 0;
			var _PID = "";
			var _ParenerInfomagion ={};
			var _NOW_HTTP_URL = "https://www.yes24.com";
			var _IsdevServer = "False";
			var _IsHttps = "True";

			this.HTTP_URL = function(){return _HTTP_URL;}
			this.NOW_HTTP_URL = function(){return _NOW_HTTP_URL;}
			this.BLOG_URL = function(){return _BLOG_URL;}
			this.IMG_HOST_IMG = function(){return _IMG_HOST_IMG;}
			this.IsHttps = function(){return _IsHttps;}
			this.IsWelcomePage = function(){return _IsWelcomePage;}
			this.MEM_AGE = function(){return _MEM_AGE;}
			this.PID = function(){return _PID;}
			this.ParenerInfomagion = function(){return _ParenerInfomagion;}
			this.IsdevServer = function(){return _IsdevServer;}
		}

		$(document).ready(function () {

		});//ready

		// 최근본 상품
		var recentViewGoods = new RecentViewGoods();

		// 광고창을 계속 불러올지 여부
		var SearchBarRenderingEnable = true;

		var USERNO = '';
		var IS_NATIVE_APPS = false;
		var is_debug = Boolean(1);
		// 브레이즈 위한 설정 값
		var TUSERNO = '';
		var isUnder14 = 'False';

	    // 스크립트 참조 여부 설정 값
	    var scToday = new Date().getFullYear() + "-" + ('0' + (new Date().getMonth() + 1)).slice(-2) + "-" + ('0' + (new Date().getDate())).slice(-2);
	    var scExpDate = "2023-07-06";   // 스크립트 참조 만료일 지정
	    var IsScExpDate = scToday > scExpDate ? false : true;
    </script>
	<script type="text/javascript" src="https://www.yes24.com/javascript/common.js?v=20260205_b"></script>
	<script type="text/javascript" src="https://www.yes24.com/JavaScript/headerSetting.js?v=20250916"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/logging/clickstream.min.js?v=20260326"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/logging/brazeSDK.js?v=20260210"></script>
	<script type="text/javascript" src="https://image.yes24.com/static/logging/brazeHelper.js?v=20260210" defer></script>
	<script src="https://image.yes24.com/static/logging/airbridgeSDK.js?v=20260210"></script>
	<script src="https://image.yes24.com/static/logging/airbridgeHelper.js?v=20260210"></script>


	<!-- 광고 스크립트 - 공통 -->
        <!-- Google Tag Manager -->
    <script>
        (function (w, d, s, l, i) {
            w[l] = w[l] || []; w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            }); var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
                    'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-WM4K93V');
    </script>
    <!-- End Google Tag Manager -->
	<script async src="https://cdn.onetag.co.kr/0/tcs.js?eid=skxx6fnq6ueeskxx6fnq6u"></script>

<link rel='stylesheet' href='https://image.yes24.com/sysimage/YESUI/detail/detail_2nd.css?ver=20260224' type='text/css' media='all'><link rel='stylesheet' href='https://image.yes24.com/sysimage/YESUI/detail/detail_class.css?ver=20260224' type='text/css' media='all'><link rel='stylesheet' href='https://image.yes24.com/sysimage/yesUI/yesUI.css?ver=20260224' type='text/css' media='all'><link rel='stylesheet' href='https://image.yes24.com/sysimage/yesUI/yesLocation.css?ver=20250818' type='text/css' media='all'>



    <!-- 구조화된 데이터 -->
    <script type="application/ld+json">
        {
            "@context": "https://schema.org",
            "@type": ["Book","Product"],
            "name": "우리가 빛의 속도로 갈 수 없다면",
            "image": "https://image.yes24.com/goods/74261416/xl",
            "description": "우리가 빛의 속도로 갈 수 없다면, “젊은 소설가의 첫 작품집이라고는 믿기지 않을 정도로 매끄럽게 이어지는 이야기 속에서 내가 생각하는 소설가의 눈과 입을 발견했다. 시선에서 질문까지, 모두 인상적이다.” -김연수(소설가)“마음을 다 맡기며 좋아할 수 있는 새...",
            "genre": ["소설/시/희곡","장르소설","SF"],
            "award": ["오늘의 작가상","한국 문학의 미래가 될 젊은 작가"],
            "keywords": "우리가빛의속도로갈수없다면, 한국문학의미래가될젊은작가, SF란시대의거울, 해외문학상_우리작가, 월간개발자_추천도서, YES24XEBS_대국민독서챌린지, 크레마클럽에있어요, 2020젊은작가TOP5, 최신작알림신청인기작가, 2021젊은작가TOP5, 가을에어울리는책,...",
            "isbn": "9791190090018",
            "bookFormat": "https://schema.org/Paperback",
            "datePublished": "2019-06-24",
            "numberOfPages": 344,
                    "inLanguage": "ko-KR",
            "url": "https://www.yes24.com/product/goods/74261416",
        "aggregateRating": {
              "@type": "AggregateRating",
              "ratingValue": 9.4,
              "reviewCount": 1926,
              "bestRating": 10.0,
              "worstRating": 0.0
            },
            "author": {
                "@type": "Person",
                "name": "김초엽"
                ,"url": "https://www.yes24.com/product/author/208250"
            },
            "publisher": {
                "@type":"Organization",
                "name":"허블"
            },
            "imageObject": {
                "@type": "ImageObject",
                "contentUrl": "https://image.yes24.com/goods/74261416/xl",
                "name": "우리가 빛의 속도로 갈 수 없다면",
                "description": "우리가 빛의 속도로 갈 수 없다면, “젊은 소설가의 첫 작품집이라고는 믿기지 않을 정도로 매끄럽게 이어지는 이야기 속에서 내가 생각하는 소설가의 눈과 입을 발견했다. 시선에서 질문까지, 모두 인상적이다.” -김연수(소설가)“마음을 다 맡기며 좋아할 수 있는 새...",
                "creditText": "YES24 제공",
                    "creator": {
                        "@type": "Organization",
                        "name": "YES24"
                    },
                "copyrightNotice": "YES24 Inc."
            },
                    "offers": {
                "@type": "Offer",
                "price": 15300,
                "priceCurrency": "KRW",
                "availability": "https://schema.org/InStock",
                "url": "https://www.yes24.com/product/goods/74261416",
                "itemCondition": "https://schema.org/NewCondition"

            },
            "workExample": [{
                "@type": "Book",
                "name": "우리가 빛의 속도로 갈 수 없다면",
                "bookFormat": "https://schema.org/EBook",
                "isbn": "9791190090025",
                "inLanguage": "ko-KR",
                "url": "https://www.yes24.com/product/goods/77220299"
                }]


        }
    </script>
</head>
<body>

	<!-- 광고 스크립트 - 공통 -->
     <!-- Google Tag Manager (noscript) -->
<noscript>
    <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WM4K93V" height="0" width="0" style="display:none;visibility:hidden"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<dl id="yesSkip">
	<dt>콘텐츠 바로가기</dt>
	<dd><a href="#wrapperContent">본문 바로가기</a></dd>
</dl>

<hr/>
<!-- !!!!!!!!!!########## 전체 페이지 영역 시작 ##########!!!!!!!!!! -->
<div id="yesWrap" class="">
	<div id="yesHeaderArea" style="">
	<!-- ########## TOPBANNER 영역 시작 ########## -->
	<section>
		<div id="upperBnWrap" style="display:none;">
			<div id="upperBnRoll">
				<div class="upperBnSet" style="display:none;">
	<div class="upperBnArea">
		<div class="upperBnSetLft" style="background-color:#f5f5ce"><a href="https://event.yes24.com/onlyApp" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0311_topbn_480x50_L_01.png" width="480" height="50" alt="도서앱"></a></div>
		<div class="upperBnSetRgt" style="background-color:#f7cce3"><a href="https://event.yes24.com/present?eventNo=267385" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0311_topbn_480x50_R_01.png" width="480" height="50" alt="폴더블독서등"></a></div>
	</div>
</div><div class="upperBnSet" style="display:none;">
	<div class="upperBnArea">
		<div class="upperBnSetLft" style="background-color:#c3e3f6"><a href="https://event.yes24.com/yesBenefit" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0311_topbn_480x50_L_02.png" width="480" height="50" alt="3월혜택"></a></div>
		<div class="upperBnSetRgt" style="background-color:#c6f1cc"><a href="https://event.yes24.com/present?eventNo=267385" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0311_topbn_480x50_R_02.png" width="480" height="50" alt="쿠션방석"></a></div>
	</div>
</div><div class="upperBnSet" style="display:none;">
	<div class="upperBnArea">
		<div class="upperBnSetLft" style="background-color:#fbf7df"><a href="https://event.yes24.com/detail?eventNo=267829" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0311_topbn_480x50_L_03.png" width="480" height="50" alt="젊은시인"></a></div>
		<div class="upperBnSetRgt" style="background-color:#f4d29d"><a href="https://event.yes24.com/present?eventNo=267385" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0311_topbn_480x50_R_03.png" width="480" height="50" alt="폴더블독서등"></a></div>
	</div>
</div>
			</div>
			<div class="upperClose"><a href="javascript:void(0);" onclick="hideUpperBn();"><em class="yBlind">TOP BANNER 닫기</em></a></div>
		</div>
	</section>
	<script type="text/javascript">
		function hideUpperBn() {
			setWcode('001_001');
			var todayDate = new Date();
			setCookie("UPPER_BN_SHOW", "OK", 1); // 오른쪽 숫자는 쿠키를 유지할 기간(day)을 설정합니다
			$("#upperBnWrap").css("display", "none");
		}

		if (getCookie("UPPER_BN_SHOW") == "") {
			$("#upperBnWrap").css("display","");
		}
		$('#upperBnRoll .upperBnSet').eq( Math.floor(Math.random()*$("#upperBnRoll .upperBnSet").length) ).show();

		//SSL 페이지에서 접근시 Top Banner 영역 제거
		if(location.href.indexOf("https://ssl.yes24.com/")> -1) {
			$("#upperBnWrap").remove();
		}
	</script>
	<!-- ########## TOPBANNER 영역 끝 ########## -->
	<!-- ########## HEADER 영역 시작 ########## -->
	<div id="yHeader">
		<h1><a class="logo" href="https://www.yes24.com/main/default.aspx" onClick="setWcode('001_004');"><svg role="img" aria-label="YES24" type="image/svg+xml"><image src="https://image.yes24.com/sysimage/renew/gnb/logoN4.png" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://image.yes24.com/sysimage/renew/gnb/logoN4.svg" width="200" height="103" alt="YES24"></image></svg></a></h1>
		<div id="yHeaderWrap">
			<!-- %%%%%%%%%% 해더 Top 영역 시작 %%%%%%%%%% -->
			<div class="yHeaderTop">
				<h2 class="yBlind">YES24 카테고리 리스트</h2>
					<ul class="cateLi" id="ulCategoryList"><li class="cate001 cateOn"><a title="국내도서" href="https://www.yes24.com/Mall/Main/Book/001?CategoryNumber=001" onclick="setWcode('001_002_001')" ><em class="txt">국내도서</em></a></li><li class="cate002"><a title="외국도서" href="https://www.yes24.com/Mall/Main/Foreign/002?CategoryNumber=002"  onclick="setWcode('001_002_002')"  ><em class="txt">외국도서</em></a></li><li class="cate018"><a title="중고샵" href="https://www.yes24.com/Mall/Main/used/018?CategoryNumber=018" onclick="setWcode('001_002_011')" ><em class="txt">중고샵</em></a></li><li class="cate017"><a title="eBook" href="https://www.yes24.com/Mall/Main/eBook/017?CategoryNumber=017" onclick="setWcode('001_002_003')"  ><em class="txt">eBook</em></a></li><li class="cateCrC"><a title="크레마클럽" href="https://cremaclub.yes24.com/BookClub/Main" onclick="setWcode('001_002_016')"  ><em class="txt">크레마클럽</em></a></li><li class="cate003"><a title="CD/LP" href="https://www.yes24.com/Mall/Main/Music/003?CategoryNumber=003" onclick="setWcode('001_002_005')" ><em class="txt">CD/LP</em></a></li><li class="cate004"><a title="DVD/Blu-ray" href="https://www.yes24.com/Mall/Main/Dvd/004?CategoryNumber=004" onclick="setWcode('001_002_006')" ><em class="txt">DVD/BD</em></a></li><li class="cate006"><a title="GIFT" href="https://www.yes24.com/Mall/Main/Gift/006?CategoryNumber=006" onclick="setWcode('001_002_009')" ><em class="txt"><u>문구</u>/GIFT</em></a></li><li class="cateENT"><a title="티켓" href="http://ticket.yes24.com" onclick="setWcode('001_002_008')" target="_blank"  ><em class="txt">티켓</em><em class="ico_newW bgGNB">새창이동</em></a></li></ul>
				<h2 class="yBlind">YES24 유틸메뉴</h2>
				<ul class="utilLi">
					<li id="LoginText">
						<input type="hidden" id="hdfLoginYn" value="N" />

							<a href="https://www.yes24.com/Templates/FTLogin.aspx" onclick="setWcode('001_003_001')"><em class="txt">로그인</em></a>

					</li>

						<li><a href="https://www.yes24.com/Member/Join/Accept.aspx" onclick="setWcode('001_003_003')">회원가입</a></li>

					<li class="myPgGrp">
						<a href="javascript:void(0);" onclick="setWcode('001_003_013')"><em class="txt">마이페이지</em><em class="ico_arrD bgGNB">하위메뉴보기</em></a>
						<dl class="myPgDl">
							<dt><a href="https://www.yes24.com/Member/FTMypageMain.aspx" onclick="setWcode('001_003_013')"><em class="txt">마이페이지</em><em class="ico_arrU bgGNB">이동</em></a></dt>
							<dd>
								<ul>
									<li><a href="https://ssl.yes24.com/MyPageOrderList/MyPageOrderList" onclick="setWcode('001_003_004')">주문내역	 </a></li>
									<li><a href="https://www.yes24.com/Member/FTGoMyBlog.aspx?type=list" onclick="setWcode('001_003_005')" target="_blank">마이리스트   </a></li>
									<li><a href="https://www.yes24.com/Templates/FTMyAccount_1YESPoint.aspx" onclick="setWcode('001_003_006')">YES포인트    </a></li>
									<li><a href="https://www.yes24.com/Templates/FTMyAccount_1YESMoney.aspx" onclick="setWcode('001_003_007')">YES머니      </a></li>
									<li><a href="https://www.yes24.com/Templates/FTMyAccount_3GiftCard.aspx" onclick="setWcode('001_003_014')">YES상품권      </a></li>
									<li><a href="https://www.yes24.com/Templates/FTMyAccount_4Coupon.aspx" onclick="setWcode('001_003_008')">쿠폰         </a></li>
									<li><a href="https://www.yes24.com/Member/MyPage_reconfirmPW.aspx" onclick="setWcode('001_003_009')">회원정보     </a></li>
								</ul>
							</dd>
						</dl>
					</li>

In [52]:
soup = BeautifulSoup(r.text, 'html.parser')
prd_detail = soup.find('div', attrs = {'id' : 'infoset_specific'})
print(prd_detail)

<div class="gd_infoSet infoSet_noLine" id="infoset_specific">
<div class="tm_infoSet">
<h4 class="tit_txt">품목정보</h4>
</div>
<div class="infoSetCont_wrap">
<div class="yesTb">
<table class="tb_nor tb_vertical" summary="품목정보 국내도서, 외국도서 " width="100%">
<caption>품목정보</caption>
<colgroup>
<col width="170"/>
<col width="*"/>
</colgroup>
<tbody class="b_size">
<tr>
<th class="txt" scope="row">발행일</th>
<td class="txt lastCol">2019년 06월 24일</td>
</tr>
<tr>
<th class="txt" scope="row">쪽수, 무게, 크기</th>
<td class="txt lastCol">344쪽 | 496g | 130*198*30mm</td>
</tr>
<tr>
<th class="txt" scope="row">ISBN13</th>
<td class="txt lastCol">9791190090018</td>
</tr>
<tr>
<th class="txt" scope="row">ISBN10</th>
<td class="txt lastCol">1190090015</td>
</tr>
</tbody>
</table>
</div>
</div>
<script type="text/javascript">
        if ($("#infoset_specific table tbody tr").length == 0) {
            $("#infoset_specific").remove();
        }
    </script>
</div>

In [53]:
prd_tr_list = prd_detail.find_all('tr')
print(prd_tr_list)

[<tr>
<th class="txt" scope="row">발행일</th>
<td class="txt lastCol">2019년 06월 24일</td>
</tr>, <tr>
<th class="txt" scope="row">쪽수, 무게, 크기</th>
<td class="txt lastCol">344쪽 | 496g | 130*198*30mm</td>
</tr>, <tr>
<th class="txt" scope="row">ISBN13</th>
<td class="txt lastCol">9791190090018</td>
</tr>, <tr>
<th class="txt" scope="row">ISBN10</th>
<td class="txt lastCol">1190090015</td>
</tr>]

In [54]:
for tr in prd_tr_list:
    if tr.find('th').get_text() == '쪽수, 무게, 크기':
        page_td = tr.find('td').get_text()
        break

In [55]:
print(page_td)

344쪽 | 496g | 130*198*30mm

In [56]:
print(page_td.split()[0])

344쪽

In [57]:
def get_page_cnt(isbn):
    url = 'http://www.yes24.com/Product/Search?domain=BOOK&query={}'
    r = requests.get(url.format(isbn))
    soup = BeautifulSoup(r.text, 'html.parser')
    prd_info = soup.find('a', attrs = {'class': 'gd_name'})
    url = 'http://www.yes24.com'+ prd_info['href']
    r = requests.get(url)
    soup = BeautifulSoup(r.text, 'html.parser')
    prd_detail = soup.find('div', attrs = {'id' : 'infoset_specific'})
    prd_tr_list = prd_detail.find_all('tr')
    for tr in prd_tr_list:
        if tr.find('th').get_text() == '쪽수, 무게, 크기':
            return tr.find('td').get_text().split()[0]
    return ''

In [58]:
get_page_cnt(9791190090018)

'344쪽'

In [59]:
top10_books = books.head(10)

In [60]:
top10_books

,no,ranking,bookname,authors,publisher,publication_year,isbn13
0,1,1,우리가 빛의 속도로 갈 수 없다면 :김초엽 소설,지은이: 김초엽,허블,2019,9791190090018
1,2,2,달러구트 꿈 백화점.이미예 장편소설,지은이: 이미예,팩토리나인,2020,9791165341909
2,3,3,지구에서 한아뿐 :정세랑 장편소설,지은이: 정세랑,난다,2019,9791188862290
3,4,4,"시선으로부터, :정세랑 장편소설",지은이: 정세랑,문학동네,2020,9788954672214
4,5,5,아몬드 :손원평 장편소설,지은이: 손원평,창비,2017,9788936434267
5,6,6,피프티 피플 :정세랑 장편소설,지은이: 정세랑,창비,2016,9788936434243
6,7,7,목소리를 드릴게요 :정세랑 소설집,지은이: 정세랑,아작,2020,9791165300005
7,8,8,나미야 잡화점의 기적 :히가시노 게이고 장편소설,지은이: 히가시노 게이고 ;옮긴이: 양윤옥,현대문학,2012,9788972756194
8,9,9,선량한 차별주의자,김지혜 지음,창비,2019,9788936477196
9,10,9,쇼코의 미소 :최은영 소설,지은이: 최은영,문학동네,2016,9788954641630

In [62]:
def get_page_cnt2(row):
    isbn = row['isbn13']
    return get_page_cnt(isbn)

In [63]:
# 나미야 잡화점의 기적 : 히가시노 게이고 장편소설 절판
# isbn13 = 9788972756194 값을 9791167901484로 변경하여 실행
top10_books['isbn13'] = top10_books['isbn13'].replace(9788972756194, 9791167901484)

/var/folders/sh/_mnj6gy531v8bk4m1yyhhth80000gn/T/ipykernel_3190/3255553915.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top10_books['isbn13'] = top10_books['isbn13'].replace(9788972756194, 9791167901484)

In [64]:
page_count = top10_books.apply(get_page_cnt2, axis=1)
print(page_count)

0    344쪽
1    300쪽
2    228쪽
3    340쪽
4    264쪽
5    396쪽
6    272쪽
7    456쪽
8    244쪽
9    296쪽
dtype: object

In [65]:
page_count = top10_books.apply(lambda row: get_page_cnt(row['isbn13']), axis=1)

In [66]:
page_count.name = 'page_count'
print(page_count)

0    344쪽
1    300쪽
2    228쪽
3    340쪽
4    264쪽
5    396쪽
6    272쪽
7    456쪽
8    244쪽
9    296쪽
Name: page_count, dtype: object

In [67]:
top10_with_page_count = pd.merge(top10_books, page_count, left_index=True, right_index=True)
top10_with_page_count

,no,ranking,bookname,authors,publisher,publication_year,isbn13,page_count
0,1,1,우리가 빛의 속도로 갈 수 없다면 :김초엽 소설,지은이: 김초엽,허블,2019,9791190090018,344쪽
1,2,2,달러구트 꿈 백화점.이미예 장편소설,지은이: 이미예,팩토리나인,2020,9791165341909,300쪽
2,3,3,지구에서 한아뿐 :정세랑 장편소설,지은이: 정세랑,난다,2019,9791188862290,228쪽
3,4,4,"시선으로부터, :정세랑 장편소설",지은이: 정세랑,문학동네,2020,9788954672214,340쪽
4,5,5,아몬드 :손원평 장편소설,지은이: 손원평,창비,2017,9788936434267,264쪽
5,6,6,피프티 피플 :정세랑 장편소설,지은이: 정세랑,창비,2016,9788936434243,396쪽
6,7,7,목소리를 드릴게요 :정세랑 소설집,지은이: 정세랑,아작,2020,9791165300005,272쪽
7,8,8,나미야 잡화점의 기적 :히가시노 게이고 장편소설,지은이: 히가시노 게이고 ;옮긴이: 양윤옥,현대문학,2012,9791167901484,456쪽
8,9,9,선량한 차별주의자,김지혜 지음,창비,2019,9788936477196,244쪽
9,10,9,쇼코의 미소 :최은영 소설,지은이: 최은영,문학동네,2016,9788954641630,296쪽